# Sample CAPA-managed EKS cluster using t3.medium workers on us-east-1.
# Note: sshKeyName is set to `default`, should be changed depending on the
# SSH key deployed in the AWS account.
apiVersion: v1
kind: Namespace
metadata:
  name: eks-cluster-1
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-cluster-1
  namespace: eks-cluster-1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: eks-cluster-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: eks-cluster-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: eks-cluster-1
  namespace: eks-cluster-1
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: eks-cluster-1-control-plane
  namespace: eks-cluster-1
spec:
  region: us-east-1
  sshKeyName: default
  version: v1.22.12
  bastion:
    enabled: false
    allowedCIDRBlocks:
    - 0.0.0.0/0
  vpcCni: 
    disable: false
  kubeProxy:
    disable: false
  endpointAccess: {}
  iamAuthenticatorConfig: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: eks-cluster-1-md-0
  namespace: eks-cluster-1
spec:
  clusterName: eks-cluster-1
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
          kind: EKSConfigTemplate
          name: eks-cluster-1-md-0
      clusterName: eks-cluster-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: eks-cluster-1-md-0
      version: v1.22.12
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: eks-cluster-1-md-0
  namespace: eks-cluster-1
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfigTemplate
metadata:
  name: eks-cluster-1-md-0
  namespace: eks-cluster-1
spec:
  template: {}
